import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UtilityProvider } from "./Context/Utility";
import { CH4FloorPlanProvider } from "./Context/CH4_FloorPlan_Context";
import { DataProvider } from "./Context/DataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative">
        <DataProvider>
          <UtilityProvider routes={["/", "/home"]}>
            <CH4FloorPlanProvider>
              <div
                style={
                  {
                    // width: "20px",
                    // height: "70px",
                  }
                }
                className="absolute flex  flex-col justify-center top-[65px] left-[65px] z-10 "
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="47"
                  height="47"
                  viewBox="0 0 64 62"
                >
                  <rect
                    x="0"
                    y="0"
                    width="64"
                    height="6"
                    rx="3"
                    fill="#979797"
                    opacity="1"
                  />
                  <rect
                    x="0"
                    y="10"
                    width="64"
                    height="6"
                    rx="3"
                    fill="#d9d9d9"
                    opacity="1"
                  />
                  <rect
                    x="0"
                    y="20"
                    width="64"
                    height="6"
                    rx="3"
                    fill="#d9d9d9"
                    opacity="0.75"
                  />
                  <rect
                    x="0"
                    y="30"
                    width="64"
                    height="6"
                    rx="3"
                    fill="#d9d9d9"
                    opacity="0.5"
                  />
                  <rect
                    x="0"
                    y="40"
                    width="64"
                    height="6"
                    rx="3"
                    fill="#d9d9d9"
                    opacity="0.25"
                  />
                  <rect
                    x="0"
                    y="50"
                    width="64"
                    height="6"
                    rx="3"
                    fill="#d9d9d9"
                    opacity="0.1"
                  />
                  <rect
                    x="0"
                    y="60"
                    width="64"
                    height="6"
                    rx="3"
                    fill="#d9d9d9"
                    opacity="0.02"
                  />
                </svg>

                {/* <div className="absolute mt-16 z-10">
                <CH4FloorPlanMenuToggle />
              </div> */}
              </div>

              {children}
            </CH4FloorPlanProvider>
          </UtilityProvider>
        </DataProvider>
      </body>
    </html>
  );
}
